### ISSUE TITLE
my own avatar

### ISSUE THREAD

**Issue by Tiandishihua** [ZhenglinZhou/HeadStudio#1]
您们的这项工作非常出色，请问是否可以生成我自己肖像的数字人来进行文本操控？

**Comment by ZhenglinZhou** [comment]
您好 @Tiandishihua，感谢您对我们工作的关注！

HeadStudio是基于文本的可驱动数字人生成。您所提到的基于用户图像/视频的数字人生成，可以考虑以下仓库：[GaussianAvatar](https://github.com/ShenhanQian/GaussianAvatars)，[GPAvatar](https://github.com/xg-chu/GPAvatar)等。

如果您还有其他问题，欢迎联系我们。
